/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as SubmitSmsRouteImport } from './routes/submit.sms'
import { Route as SubmitEmailRouteImport } from './routes/submit.email'
import { Route as ResearchApiDocsRouteImport } from './routes/research.api-docs'
import { Route as LearnProfessionalsIndexRouteImport } from './routes/learn.professionals.index'
import { Route as LearnIndividualsIndexRouteImport } from './routes/learn.individuals.index'
import { Route as LearnProfessionalsChapterSlugRouteImport } from './routes/learn.professionals.$chapterSlug'
import { Route as LearnIndividualsChapterSlugRouteImport } from './routes/learn.individuals.$chapterSlug'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitSmsRoute = SubmitSmsRouteImport.update({
  id: '/submit/sms',
  path: '/submit/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitEmailRoute = SubmitEmailRouteImport.update({
  id: '/submit/email',
  path: '/submit/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchApiDocsRoute = ResearchApiDocsRouteImport.update({
  id: '/research/api-docs',
  path: '/research/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnProfessionalsIndexRoute = LearnProfessionalsIndexRouteImport.update({
  id: '/learn/professionals/',
  path: '/learn/professionals/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndividualsIndexRoute = LearnIndividualsIndexRouteImport.update({
  id: '/learn/individuals/',
  path: '/learn/individuals/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnProfessionalsChapterSlugRoute =
  LearnProfessionalsChapterSlugRouteImport.update({
    id: '/learn/professionals/$chapterSlug',
    path: '/learn/professionals/$chapterSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnIndividualsChapterSlugRoute =
  LearnIndividualsChapterSlugRouteImport.update({
    id: '/learn/individuals/$chapterSlug',
    path: '/learn/individuals/$chapterSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dataset': typeof DatasetRoute
  '/license': typeof LicenseRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/research/api-docs': typeof ResearchApiDocsRoute
  '/submit/email': typeof SubmitEmailRoute
  '/submit/sms': typeof SubmitSmsRoute
  '/learn': typeof LearnIndexRoute
  '/research': typeof ResearchIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/learn/individuals/$chapterSlug': typeof LearnIndividualsChapterSlugRoute
  '/learn/professionals/$chapterSlug': typeof LearnProfessionalsChapterSlugRoute
  '/learn/individuals': typeof LearnIndividualsIndexRoute
  '/learn/professionals': typeof LearnProfessionalsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dataset': typeof DatasetRoute
  '/license': typeof LicenseRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/research/api-docs': typeof ResearchApiDocsRoute
  '/submit/email': typeof SubmitEmailRoute
  '/submit/sms': typeof SubmitSmsRoute
  '/learn': typeof LearnIndexRoute
  '/research': typeof ResearchIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/learn/individuals/$chapterSlug': typeof LearnIndividualsChapterSlugRoute
  '/learn/professionals/$chapterSlug': typeof LearnProfessionalsChapterSlugRoute
  '/learn/individuals': typeof LearnIndividualsIndexRoute
  '/learn/professionals': typeof LearnProfessionalsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dataset': typeof DatasetRoute
  '/license': typeof LicenseRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/research/api-docs': typeof ResearchApiDocsRoute
  '/submit/email': typeof SubmitEmailRoute
  '/submit/sms': typeof SubmitSmsRoute
  '/learn/': typeof LearnIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/learn/individuals/$chapterSlug': typeof LearnIndividualsChapterSlugRoute
  '/learn/professionals/$chapterSlug': typeof LearnProfessionalsChapterSlugRoute
  '/learn/individuals/': typeof LearnIndividualsIndexRoute
  '/learn/professionals/': typeof LearnProfessionalsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dataset'
    | '/license'
    | '/partners'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/research/api-docs'
    | '/submit/email'
    | '/submit/sms'
    | '/learn'
    | '/research'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/learn/individuals/$chapterSlug'
    | '/learn/professionals/$chapterSlug'
    | '/learn/individuals'
    | '/learn/professionals'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dataset'
    | '/license'
    | '/partners'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/research/api-docs'
    | '/submit/email'
    | '/submit/sms'
    | '/learn'
    | '/research'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/learn/individuals/$chapterSlug'
    | '/learn/professionals/$chapterSlug'
    | '/learn/individuals'
    | '/learn/professionals'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dataset'
    | '/license'
    | '/partners'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/research/api-docs'
    | '/submit/email'
    | '/submit/sms'
    | '/learn/'
    | '/research/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/learn/individuals/$chapterSlug'
    | '/learn/professionals/$chapterSlug'
    | '/learn/individuals/'
    | '/learn/professionals/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DatasetRoute: typeof DatasetRoute
  LicenseRoute: typeof LicenseRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  ResearchApiDocsRoute: typeof ResearchApiDocsRoute
  SubmitEmailRoute: typeof SubmitEmailRoute
  SubmitSmsRoute: typeof SubmitSmsRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  LearnIndividualsChapterSlugRoute: typeof LearnIndividualsChapterSlugRoute
  LearnProfessionalsChapterSlugRoute: typeof LearnProfessionalsChapterSlugRoute
  LearnIndividualsIndexRoute: typeof LearnIndividualsIndexRoute
  LearnProfessionalsIndexRoute: typeof LearnProfessionalsIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/sms': {
      id: '/submit/sms'
      path: '/submit/sms'
      fullPath: '/submit/sms'
      preLoaderRoute: typeof SubmitSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/email': {
      id: '/submit/email'
      path: '/submit/email'
      fullPath: '/submit/email'
      preLoaderRoute: typeof SubmitEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/api-docs': {
      id: '/research/api-docs'
      path: '/research/api-docs'
      fullPath: '/research/api-docs'
      preLoaderRoute: typeof ResearchApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/professionals/': {
      id: '/learn/professionals/'
      path: '/learn/professionals'
      fullPath: '/learn/professionals'
      preLoaderRoute: typeof LearnProfessionalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/individuals/': {
      id: '/learn/individuals/'
      path: '/learn/individuals'
      fullPath: '/learn/individuals'
      preLoaderRoute: typeof LearnIndividualsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/professionals/$chapterSlug': {
      id: '/learn/professionals/$chapterSlug'
      path: '/learn/professionals/$chapterSlug'
      fullPath: '/learn/professionals/$chapterSlug'
      preLoaderRoute: typeof LearnProfessionalsChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/individuals/$chapterSlug': {
      id: '/learn/individuals/$chapterSlug'
      path: '/learn/individuals/$chapterSlug'
      fullPath: '/learn/individuals/$chapterSlug'
      preLoaderRoute: typeof LearnIndividualsChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DatasetRoute: DatasetRoute,
  LicenseRoute: LicenseRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  ResearchApiDocsRoute: ResearchApiDocsRoute,
  SubmitEmailRoute: SubmitEmailRoute,
  SubmitSmsRoute: SubmitSmsRoute,
  LearnIndexRoute: LearnIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  LearnIndividualsChapterSlugRoute: LearnIndividualsChapterSlugRoute,
  LearnProfessionalsChapterSlugRoute: LearnProfessionalsChapterSlugRoute,
  LearnIndividualsIndexRoute: LearnIndividualsIndexRoute,
  LearnProfessionalsIndexRoute: LearnProfessionalsIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
