// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountSubmissions(ctx context.Context) (int64, error)
	CountSubmissionsByCategory(ctx context.Context, category *string) (int64, error)
	CountSubmissionsByType(ctx context.Context, type_ SubmissionType) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, role NullUserRole) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredTokens(ctx context.Context) error
	DeleteSubmission(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetLeaderboard(ctx context.Context) ([]GetLeaderboardRow, error)
	GetStatistics(ctx context.Context) (Statistic, error)
	GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByResetToken(ctx context.Context, resetToken *string) (User, error)
	GetUserByVerificationToken(ctx context.Context, verificationToken *string) (User, error)
	ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]Submission, error)
	ListSubmissionsByCategory(ctx context.Context, arg ListSubmissionsByCategoryParams) ([]Submission, error)
	ListSubmissionsByDateRange(ctx context.Context, arg ListSubmissionsByDateRangeParams) ([]Submission, error)
	ListSubmissionsByStatus(ctx context.Context, arg ListSubmissionsByStatusParams) ([]Submission, error)
	ListSubmissionsByType(ctx context.Context, arg ListSubmissionsByTypeParams) ([]Submission, error)
	ListUserTokens(ctx context.Context, arg ListUserTokensParams) ([]ApiToken, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	RevokeToken(ctx context.Context, id uuid.UUID) error
	UpdateStatistics(ctx context.Context) error
	UpdateSubmissionContent(ctx context.Context, arg UpdateSubmissionContentParams) (Submission, error)
	UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) (Submission, error)
	UpdateTokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateUserApproval(ctx context.Context, arg UpdateUserApprovalParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserResetToken(ctx context.Context, arg UpdateUserResetTokenParams) (User, error)
	UpdateUserVerification(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
