// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package database

import (
	"context"
)

const getStatistics = `-- name: GetStatistics :one
SELECT id, total_submissions, submissions_by_type, submissions_by_category, submissions_by_status, languages_detected, submissions_by_date, updated_at FROM statistics WHERE id = 1
`

func (q *Queries) GetStatistics(ctx context.Context) (Statistic, error) {
	row := q.db.QueryRow(ctx, getStatistics)
	var i Statistic
	err := row.Scan(
		&i.ID,
		&i.TotalSubmissions,
		&i.SubmissionsByType,
		&i.SubmissionsByCategory,
		&i.SubmissionsByStatus,
		&i.LanguagesDetected,
		&i.SubmissionsByDate,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStatistics = `-- name: UpdateStatistics :exec
SELECT update_statistics()
`

func (q *Queries) UpdateStatistics(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateStatistics)
	return err
}
