// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (
    user_id, token_hash, expires_at, user_agent, ip_address
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, token_hash, expires_at, revoked, revoked_at, last_used_at, user_agent, ip_address, created_at
`

type CreateAPITokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	UserAgent *string   `json:"user_agent"`
	IpAddress *string   `json:"ip_address"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM api_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked, revoked_at, last_used_at, user_agent, ip_address, created_at FROM api_tokens
WHERE token_hash = $1 AND NOT revoked AND expires_at > NOW()
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listUserTokens = `-- name: ListUserTokens :many
SELECT id, user_id, token_hash, expires_at, revoked, revoked_at, last_used_at, user_agent, ip_address, created_at FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserTokensParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserTokens(ctx context.Context, arg ListUserTokensParams) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listUserTokens, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.UserAgent,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE api_tokens
SET revoked = TRUE, revoked_at = NOW()
WHERE user_id = $1 AND NOT revoked
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE api_tokens
SET revoked = TRUE, revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeToken, id)
	return err
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateTokenLastUsed, id)
	return err
}
