// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = $1 AND deleted_at IS NULL
`

func (q *Queries) CountUsersByRole(ctx context.Context, role NullUserRole) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, role, organization, purpose, verification_token, verification_expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	Role                  NullUserRole       `json:"role"`
	Organization          *string            `json:"organization"`
	Purpose               *string            `json:"purpose"`
	VerificationToken     *string            `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Organization,
		arg.Purpose,
		arg.VerificationToken,
		arg.VerificationExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE reset_token = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByResetToken(ctx context.Context, resetToken *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, resetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE verification_token = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Organization,
			&i.Purpose,
			&i.Verified,
			&i.Approved,
			&i.VerificationToken,
			&i.VerificationExpiresAt,
			&i.ResetToken,
			&i.ResetExpiresAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE role = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByRoleParams struct {
	Role   NullUserRole `json:"role"`
	Limit  int32        `json:"limit"`
	Offset int32        `json:"offset"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Organization,
			&i.Purpose,
			&i.Verified,
			&i.Approved,
			&i.VerificationToken,
			&i.VerificationExpiresAt,
			&i.ResetToken,
			&i.ResetExpiresAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserApproval = `-- name: UpdateUserApproval :one
UPDATE users
SET approved = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserApprovalParams struct {
	ID       uuid.UUID `json:"id"`
	Approved *bool     `json:"approved"`
}

func (q *Queries) UpdateUserApproval(ctx context.Context, arg UpdateUserApprovalParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserApproval, arg.ID, arg.Approved)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2, reset_token = NULL, reset_expires_at = NULL
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserResetToken = `-- name: UpdateUserResetToken :one
UPDATE users
SET reset_token = $2, reset_expires_at = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserResetTokenParams struct {
	ID             uuid.UUID          `json:"id"`
	ResetToken     *string            `json:"reset_token"`
	ResetExpiresAt pgtype.Timestamptz `json:"reset_expires_at"`
}

func (q *Queries) UpdateUserResetToken(ctx context.Context, arg UpdateUserResetTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserResetToken, arg.ID, arg.ResetToken, arg.ResetExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :one
UPDATE users
SET verified = TRUE, verification_token = NULL, verification_expires_at = NULL
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, role, organization, purpose, verified, approved, verification_token, verification_expires_at, reset_token, reset_expires_at, last_login_at, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateUserVerification(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, updateUserVerification, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Organization,
		&i.Purpose,
		&i.Verified,
		&i.Approved,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.ResetToken,
		&i.ResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
